# application.yaml takes priority over the application.properties file
spring:
  application:
    name: store
    payment-gateway: paypal

stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP
  
payment-gateway: paypal

mail:
  host: https://smtp.gmail.com
  port: 5761