# application.yaml takes priority over the application.properties file
spring:
  application:
    name: store
    payment-gateway: paypal
  datasource:
    url: jdbc:mysql://localhost:8306/store?createDatabaseIfNotExist=true
    username: dbuser
    password: dbpw
  # jpa:
  #   hibernate:
  #     ddl-auto: "create" # runs migrations automatially (other options: create, create-drop, validate, update)
  # TODO: hibernate - ddl-auto not properly working because schema are not 100% compatible with hybernate.
  # need to update schema definitions in order for this to work. use db-migrate make command instead

stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 1000
  supported-currencies: USD,EUR,GBP
  
payment-gateway: paypal

mail:
  host: https://smtp.gmail.com
  port: 5761