package com.springbootfundamentals.repositoryExamples;

import org.springframework.context.ConfigurableApplicationContext;

import com.springbootfundamentals.store.entities.User;
import com.springbootfundamentals.store.repositories.UserRepository;

public class RepositoryExamples {
    ConfigurableApplicationContext context;

    public RepositoryExamples(ConfigurableApplicationContext appContext) {
        this.context = appContext;
    }

    public void main() {
        /**
		 * Examples
		 */

		usingRepositories();
    }

    public void usingRepositories() {
        // note: the UserRepository class is generated by springboot at run time (we didn't create this class, only the interface)   
		var repository = context.getBean(UserRepository.class);

        // create and save user
		var user = User.builder()
			.name("John")
			.email("john@gmail.com")
			.password("password")
			.build();

		repository.save(user);

        // find user by id
        var user1 = repository.findById(1L).orElseThrow(); // alternatively return null: orElse(null)
        System.out.println(user1.getEmail());

        repository.findAll().forEach(u -> System.out.println(u.getEmail()));

        // delete user by id
        repository.deleteById(1L);
    }
}
